CREATE TABLE IF NOT EXISTS users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_name VARCHAR(255)                            NOT NULL,
    email     VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories
(
    category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (category_name)
);

CREATE TABLE IF NOT EXISTS locations
(
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat         REAL                                    NOT NULL,
    lon         REAL                                    NOT NULL,
    CONSTRAINT pk_location PRIMARY KEY (location_id)
    );

CREATE TABLE IF NOT EXISTS events
(
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY                              NOT NULL,
    annotation         VARCHAR(512)                                               NOT NULL,
    category_id BIGINT REFERENCES categories (category_id)                        NOT NULL,
    confirmed_requests BIGINT                                                     NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP      NOT NULL,
    description        VARCHAR(512)                                               NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                                NOT NULL,
    initiator_id       BIGINT REFERENCES users (user_id)                          NOT NULL,
    location_id        BIGINT REFERENCES locations (location_id)                  NOT NULL,
    paid               BOOLEAN                                                    NOT NULL,
    participant_limit  int                                                        NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE                                NOT NULL,
    request_moderation BOOLEAN                                                    NOT NULL,
    state_name         VARCHAR(512)                                               NOT NULL,
    title              VARCHAR(512)                                               NOT NULL,
    views              BIGINT,
    CONSTRAINT pk_event PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS participation
(
    participation_id BIGINT GENERATED BY DEFAULT AS IDENTITY                  NOT NULL,
    created          TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP    NOT NULL,
    event_id         BIGINT REFERENCES events (event_id)                      NOT NULL,
    requester_id     BIGINT REFERENCES users (user_id)                        NOT NULL,
    state_name       varchar(256)                                             NOT NULL,
    CONSTRAINT pk_participation PRIMARY KEY (participation_id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
    pinned         boolean                                        NOT NULL,
    title          VARCHAR(512)                                   NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT REFERENCES compilations (compilation_id)        NOT NULL,
    event_id BIGINT REFERENCES events (event_id)                          NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);