CREATE TABLE IF NOT EXISTS hits
(
    hit_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        varchar(128)                            NOT NULL,
    uri        varchar(128)                            NOT NULL,
    ip         varchar(15)                            NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT PK_HITS PRIMARY KEY (hit_id)
);